name: CI workflow for CGPA calculate app

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Super-Linter
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for commenting on PRs
        DEBUG: true