name: CI workflow for CGPA calculate app

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for commenting on PRs
          DEBUG: true

      - name: Run tests with pytest
        run: |
          pytest

  merge-pr:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.15.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: merge
          required_labels: automerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
